const data = {{ifid: "IC001S",url: "/MasterOperationAPI/translation",lamdbda: ""},
{ifid: "IC002S",url:  "/MasterOperationAPI/translationgroup",lamdbda: ""},
{ifid: "IC003S",url:  "/MasterOperationAPI/translationeconnect",lamdbda: ""},
{ifid: "IC101S",url:  "/FactoryDataAPI/RegisterFactoryData",lamdbda: ""},
{ifid: "IT101C",url:  "/FactoryDataAPI/RegisterFactoryDataNotification",lamdbda: ""},
{ifid: "IC102S", url:  "/FactoryDataAPI/", lamdbda: ""},
{ifid: "IT102C",url:  "/FactoryDataAPI/ReplaceFactoryDataNotification",lamdbda: ""},
{ifid: "IC103S",url:  "/DCMProvisioningAPI/requests/", lamdbda: ""},
{ifid: "IT103C",url:  "/DCMProvisioningAPI/DCMProvisioningNotification",lamdbda: ""},
{ifid: "IT201E",url:  "/IgnitionNotification/IgnitionNotification",lamdbda: ""},
{ifid: "IT207R",url:  "/UploadVPNotification/VehicleProbeNotification",lamdbda: ""},
{ifid: "IT208E",url:  "/eConnectTripNotification/eConnectTripDataNotification",lamdbda: ""},
{ifid: "IC209O",url:  "/eConnectRealTimeStatusRequestsAPI/requests/", lamdbda: ""},
{ifid: "IT209C",url:  "/eConnectRealTimeStatusRequestsAPI/eConnectReal-TimeStatusResultNotification",lamdbda: ""},
{ifid: "IT301E",url:  "/UBIAPI/UBIThresholdExceedingNotification",lamdbda: ""},
{ifid: "IT302E",url:  "/WarningNotification/WarningNotification",lamdbda: ""},
{ifid: "IT303E",url:  "/AllDiagnosticsAPI/DTCNotification",lamdbda: ""},
{ifid: "IT304E",url:  "/AllDiagnosticsAPI/FFDNotification",lamdbda: ""},
{ifid: "IT305E",url:  "/AllDiagnosticsAPI/LastNotification",lamdbda: ""},
{ifid: "IT306E",url:  "/AlarmReportAPI/AlarmNotification",lamdbda: ""},
{ifid: "IT307E",url:  "/SVTAPI/TOWNotification",lamdbda: ""},
{ifid: "IT308E",url:  "/eConnectRealTimeStatusRequestsAPI/eConnectRemoteConfirmNotification",lamdbda: ""},
{ifid: "IT309E",url:  "/eConnectEventNotification/eConnectEventNotification",lamdbda: ""},
{ifid: "IT310E",url:  "/eConnectStatusChangeNotification/eConnectStatusChangeNotification",lamdbda: ""},
{ifid: "IC311O",url:  "/LocalServerCommunicationAPI/requests/", lamdbda: ""},
{ifid: "IC312O",url:  "/LocalServerCommunicationAPI/displayrequests/", lamdbda: ""},
{ifid: "IT311C",url:  "/LocalServerCommunicationAPI/LocalServerCommunicationNotification",lamdbda: ""},
{ifid: "IC202S",url:  "/VPConditionFileAPI/emergencyflag",lamdbda: ""},
{ifid: "IC203S",url:  "/VPConditionFileAPI/emergency/", lamdbda: ""},
{ifid: "IC204S",url:  "/VPConditionFileAPI/unique/",lamdbda: ""},
{ifid: "IC210S", url:  "/VPConditionFileAPI/unique/", lamdbda: ""},
{ifid: "IC205S",url:  "/VPConditionFileAPI/dpccartype/", lamdbda: ""},
{ifid: "IC206S",url:  "/VPConditionFileAPI/default/", lamdbda: ""},
{ifid: "IC401O",url:  "/eConnectRemoteControlAPI/requests/", lamdbda: ""},
{ifid: "IT401C",url:  "/eConnectRemoteControlAPI/eConnectRemoteControlResultNotification",lamdbda: ""},
{ifid: "IC501O",url:  "/RemoteControlAPI/requests/", lamdbda: ""},
{ifid: "IT501C",url:  "/RemoteControlAPI/RemoteControlResultNotification",lamdbda: ""},
{ifid: "IC502O",url:  "/RemoteImmobilizerAPI/requests/", lamdbda: ""},
{ifid: "IT502C",url:  "/RemoteImmobilizerAPI/RemoteImmobilizerNotification",lamdbda: ""},
{ifid: "IC601O",url:  "/AllDiagnosticsAPI/", lamdbda: ""},
{ifid: "IC602O",url:  "/RemoteMonitoringAPI/schedule/", lamdbda: ""},
{ifid: "IT602C",url:  "/RemoteMonitoringAPI/RemoteMonitoringNotification",lamdbda: ""},
{ifid: "IC603O",url:  "/SVTAPI/requests/periodic/", lamdbda: ""},
{ifid: "IT603R",url:  "/SVTAPI/SVTNotification",lamdbda: ""},
{ifid: "IC604O",url: "/SVTAPI/requests/periodic/", lamdbda: ""}
}
module.exports = data;
