new Ifid("IC001S", "POST", "/MasterOperationAPI/translation", null, true, null),
			new Ifid("IC002S", "POST", "/MasterOperationAPI/translationgroup", null, true, null),
			new Ifid("IC003S", "POST", "/MasterOperationAPI/translationeconnect", null, true, null),
			new Ifid("IC101S", "POST", "/FactoryDataAPI/RegisterFactoryData", null, true, null),
			new Ifid("IT101C", "POST", "/FactoryDataAPI/RegisterFactoryDataNotification", null, true, null),
			new Ifid("IC102S", "PUT",  "/FactoryDataAPI/(.+)", new String[] { "vin" }, true, null),
			new Ifid("IT102C", "POST", "/FactoryDataAPI/ReplaceFactoryDataNotification", null, true, null),
			new Ifid("IC103S", "POST", "/DCMProvisioningAPI/requests/(.+)", new String[] { "vin" }, true, null),
			new Ifid("IT103C", "POST", "/DCMProvisioningAPI/DCMProvisioningNotification", null, true, null),
			new Ifid("IT201E", "POST", "/IgnitionNotification/IgnitionNotification", null, true, null),
			new Ifid("IT207R", "POST", "/UploadVPNotification/VehicleProbeNotification", null, true, null),
			new Ifid("IT208E", "POST", "/eConnectTripNotification/eConnectTripDataNotification", null, true, null),
			new Ifid("IC209O", "POST", "/eConnectRealTimeStatusRequestsAPI/requests/(.+)", new String[] { "vin" }, true, null),
			new Ifid("IT209C", "POST", "/eConnectRealTimeStatusRequestsAPI/eConnectReal-TimeStatusResultNotification", null, true, null),
			new Ifid("IT301E", "POST", "/UBIAPI/UBIThresholdExceedingNotification", null, true, null),
			new Ifid("IT302E", "POST", "/WarningNotification/WarningNotification", null, true, null),
			new Ifid("IT303E", "POST", "/AllDiagnosticsAPI/DTCNotification", null, true, null),
			new Ifid("IT304E", "POST", "/AllDiagnosticsAPI/FFDNotification", null, true, null),
			new Ifid("IT305E", "POST", "/AllDiagnosticsAPI/LastNotification", null, true, null),
			new Ifid("IT306E", "POST", "/AlarmReportAPI/AlarmNotification", null, true, null),
			new Ifid("IT307E", "POST", "/SVTAPI/TOWNotification", null, true, null),
			new Ifid("IT308E", "POST", "/eConnectRealTimeStatusRequestsAPI/eConnectRemoteConfirmNotification", null, true, null),
			new Ifid("IT309E", "POST", "/eConnectEventNotification/eConnectEventNotification", null, true, null),
			new Ifid("IT310E", "POST", "/eConnectStatusChangeNotification/eConnectStatusChangeNotification", null, true, null),
			new Ifid("IC311O", "POST", "/LocalServerCommunicationAPI/requests/(.+)", new String[] { "vin" }, false, null),
			new Ifid("IC312O", "POST", "/LocalServerCommunicationAPI/displayrequests/(.+)", new String[] { "vin" }, true, null),
			new Ifid("IT311C", "POST", "/LocalServerCommunicationAPI/LocalServerCommunicationNotification", null, true, null),
			new Ifid("IC202S", "POST", "/VPConditionFileAPI/emergencyflag", null, false, new String[] { "EmergencyFlag" }),
			new Ifid("IC203S", "POST", "/VPConditionFileAPI/emergency/(.+)/(.+)", new String[] { "region", "generation" }, true, null),
			new Ifid("IC204S", "POST", "/VPConditionFileAPI/unique/(.+)/(.+)", new String[] { "region", "generation" }, true, new String[] { "id", "unittype" }),
			new Ifid("IC210S", "DELETE", "/VPConditionFileAPI/unique/(.+)/(.+)", new String[] { "region", "generation" }, false, new String[] { "id", "unittype" }),
			new Ifid("IC205S", "POST", "/VPConditionFileAPI/dpccartype/(.+)/(.+)", new String[] { "region", "generation" }, true, new String[] { "dpccartypes" }),
			new Ifid("IC206S", "POST", "/VPConditionFileAPI/default/(.+)/(.+)", new String[] { "region", "generation" }, true, null),
			new Ifid("IC401O", "POST", "/eConnectRemoteControlAPI/requests/(.+)", new String[] { "vin" }, true, null),
			new Ifid("IT401C", "POST", "/eConnectRemoteControlAPI/eConnectRemoteControlResultNotification", null, true, null),
			new Ifid("IC501O", "POST", "/RemoteControlAPI/requests/(.+)", new String[] { "vin" }, true, null),
			new Ifid("IT501C", "POST", "/RemoteControlAPI/RemoteControlResultNotification", null, true, null),
			new Ifid("IC502O", "POST", "/RemoteImmobilizerAPI/requests/(.+)", new String[] { "vin" }, true, null),
			new Ifid("IT502C", "POST", "/RemoteImmobilizerAPI/RemoteImmobilizerNotification", null, true, null),
			new Ifid("IC601O", "POST", "/AllDiagnosticsAPI/(.+)", new String[] { "vin" }, false, null),
			new Ifid("IC602O", "POST", "/RemoteMonitoringAPI/schedule/(.+)", new String[] { "vin" }, true, null),
			new Ifid("IT602C", "POST", "/RemoteMonitoringAPI/RemoteMonitoringNotification", null, true, null),
			new Ifid("IC603O", "POST", "/SVTAPI/requests/periodic/(.+)", new String[] { "vin" }, true, null),
			new Ifid("IT603R", "POST", "/SVTAPI/SVTNotification", null, true, null),
			new Ifid("IC604O", "DELETE", "/SVTAPI/requests/periodic/(.+)", new String[] { "vin" }, 
