# 触发方式为手动触发workflow
on:
 workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'development'
# 执行newman.js
jobs:
  run_js:
    runs-on: ubuntu-latest
    steps:
    - name: 配置 AWS 凭证
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: ap-south-1 # 替换为你的区域
    - name: Checkout code
      uses: actions/checkout@v2
    # 配置node版本 
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    # 安装aws-sdk插件
    - name: install aws-sdk
      run: npm install aws-sdk
    - name: ls aws-sdk
      run: npm ls aws-sdk
    # 安装newman插件
    - name: install Newman
      run: npm install newman
    - name: Run JavaScript code
      run: |
        echo 'Run newman.js'
        # 执行newman.js
        node newman/newman.js
