name: My Workflow

on:
 workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'development'

jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
     - name: Get IP
       run: |
          # Commands to get the IP address
          echo "::set-output name=ip::$(curl -s https://api.ipify.org)"
     - name: Run Job A
       run: |
          # Your Job A steps here
          echo "This is Job A"
          exit 1  # Simulate a failure if needed

  jobB:
    needs: jobA
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Run JavaScript code
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Read IP from Job A
        id: read-ip
        run: |
          echo "IP=${{ needs.jobA.outputs.ip }}" >> $GITHUB_ENV
      - name: Print IP in JavaScript
        run: |
          node -e "console.log(process.env.IP)"
