name: My Workflow

on:
 workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'development'

jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
     - name: Get IP
       run: |
          # Commands to get the IP address and store it in an environment variable
          echo "IP=$(curl -s https://api.ipify.org)" >> $GITHUB_ENV
       id: ip
     - name: Run Job A
       run: |
          # Your Job A steps here
          echo "This is Job A"
          exit 1  # Simulate a failure if needed

  jobB:
    needs: jobA
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Print IP from Job A
        run: |
          echo "The IP address from Job A is ${{ env.IP }}"
      - name: Run Job B
        run: echo "This is Job B"
