name: My Workflow

on:
 workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'development'

jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
     - name: Get IP
       run: |
          # Commands to get the IP address and store it in a file
          echo "$(curl -s https://api.ipify.org)" > ip.txt
       id: ip
     - name: Upload IP artifact
       uses: actions/upload-artifact@v2
       with:
         name: ip-address
         path: ip.txt
     - name: Read IP from file
       run: |
          cat ip.txt
     - name: Run Job A
       run: |
          # Your Job A steps here
          echo "This is Job A"
          exit 1  # Simulate a failure if needed

  jobB:
    needs: jobA
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Download IP artifact
        uses: actions/download-artifact@v2
        with:
          name: ip-address
      - name: Read IP from file
        run: |
          cat ip.txt
      - name: Run Job B
        run: echo "This is Job B"
