name: Execute Python with Boto3

on:
 workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'development'

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # 指定为 3.x

    - name: Install dependencies
      run: pip install aws-sdk-python

    - name: Connect to AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # 将AWS访问密钥ID存储在GitHub仓库的secrets中
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # 将AWS访问密钥存储在GitHub仓库的secrets中
        AWS_REGION: ap-south-1 # 将此替换为你使用的AWS区域
      run: python newman/test.py # 替换为你要运行的Python脚本
